GET http://localhost:8080/user

###
PUT http://localhost:8080/user
Authorization: Basic user password
Content-Type: application/json

{
  "email": "updateduser@gmail.com",
  "name": "updateduser",
  "friends": [
    "someone1",
    "someone2"
  ]
}

###
DELETE http://localhost:8080/user
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
POST http://localhost:8080/user
Content-Type: application/json

{
  "email": "newuser@gmail.com",
  "name": "newuser",
  "friends": [
    "someone1",
    "someone2"
  ]
}

###

GET http://localhost:8080/users?age=30

###
GET http://localhost:8080/users/-1
