GET http://localhost:8080/api/users

###
PUT http://localhost:8080/user
Authorization: Basic user password
Content-Type: application/json

{
  "email": "updateduser@gmail.com",
  "name": "updateduser",
  "friends": [
    "someone1",
    "someone2"
  ]
}

###
DELETE http://localhost:8080/api/users/1

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "newuser@gmail.com",
  "name": "newuser"
}

###

GET http://localhost:8080/api/users?age=0

###
GET http://localhost:8080/api/users/1
